/zhome/bb/9/212485/.lsbatch/1732100157.23221369.shell: line 14: source: .env: file not found
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 23, in <module>
    from transformers import pipeline
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 23, in <module>
    from transformers import pipeline
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 3, in <module>
    from transformers import pipeline
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 3, in <module>
    from transformers import pipeline
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 3, in <module>
    from transformers import pipeline
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl9/python/3.10.12/include/python3.10/UNKNOWN
sysconfig: /appl9/python/3.10.12/include/python3.10
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
  WARNING: The scripts f2py and numpy-config are installed in '/zhome/bb/9/212485/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/bb/9/212485/.local/include/python3.10/UNKNOWN
sysconfig: /zhome/bb/9/212485/.local/include/python3.10
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 24.3.1 is available.
You should consider upgrading via the '/appl9/python/3.10.12/bin/python3 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 10, in <module>
    import pandas
ModuleNotFoundError: No module named 'pandas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 13, in <module>
    import pandas
ModuleNotFoundError: No module named 'pandas'
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 2, in <module>
    from sklearn.preprocessing import StandardScaler
ModuleNotFoundError: No module named 'sklearn'
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/12.1
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 2, in <module>
    from sklearn.preprocessing import StandardScaler
ModuleNotFoundError: No module named 'sklearn'
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/11.3
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
User defined signal 2
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/11.3
Traceback (most recent call last):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 91, in <module>
    sentiments_with_scores = process_in_batches(combined_data, batch_size)
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/sentiment_analysis.py", line 75, in process_in_batches
    for i, batch in enumerate(dataloader):
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 398, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 171, in collate
    {
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 172, in <dictcomp>
    key: collate(
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 155, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/zhome/bb/9/212485/DTUDataScienceProject/myproject/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 272, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 188] at entry 0 and [1, 38] at entry 1
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/11.3
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
User defined signal 2
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/11.3
User defined signal 2
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/11.3
Loaded dependency [python3/3.10.12]: sqlite3/3.42.0
Loaded module: python3/3.10.12

Loading python3/3.10.12
  Loading requirement: sqlite3/3.42.0
Loaded module: cuda/11.3
